"""Generate a lesson-plan DOCX file from intent + retrieval context."""
from __future__ import annotations

import datetime
from typing import Any

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Pt, RGBColor


def _safe_list(value: Any) -> list[str]:
    if not isinstance(value, list):
        return []
    return [str(item).strip() for item in value if str(item).strip()]


def generate_docx(
    intent: dict,
    rag_chunks: list[str],
    output_path: str,
    evidence_entries: list[dict[str, Any]] | None = None,
) -> str:
    topic = str(intent.get("topic") or "Course Topic")
    audience = str(intent.get("audience") or "Learners")
    duration = str(intent.get("duration") or "45 minutes")
    style = str(intent.get("style") or "Structured")
    teaching_goal = str(intent.get("teaching_goal") or "Help learners understand and apply key concepts.")
    difficulty_focus = str(intent.get("difficulty_focus") or "Key difficult points")
    key_points = _safe_list(intent.get("key_points")) or ["Core concept", "Principle", "Application"]
    today = datetime.date.today().strftime("%Y-%m-%d")

    doc = Document()

    title = doc.add_heading(f"{topic} - Lesson Plan", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    info = doc.add_table(rows=5, cols=2)
    info.style = "Table Grid"
    rows = [
        ("Topic", topic),
        ("Audience", audience),
        ("Duration", duration),
        ("Style", style),
        ("Generated At", today),
    ]
    for idx, (k, v) in enumerate(rows):
        info.rows[idx].cells[0].text = k
        info.rows[idx].cells[1].text = v

    doc.add_heading("Teaching Goal", level=1)
    doc.add_paragraph(teaching_goal)

    doc.add_heading("Difficulty Focus", level=1)
    doc.add_paragraph(difficulty_focus)

    doc.add_heading("Key Points", level=1)
    for item in key_points:
        p = doc.add_paragraph(style="List Bullet")
        p.add_run(item)

    doc.add_heading("Suggested Teaching Flow", level=1)
    flow = [
        ("Warm-up (5 min)", "Introduce a practical scenario and activate prior knowledge."),
        ("Concept Explanation (15 min)", "Explain core concepts and connect them with examples."),
        ("Guided Practice (15 min)", "Lead students through one or two representative tasks."),
        ("Wrap-up (10 min)", "Summarize takeaways and assign extension work."),
    ]
    for section, desc in flow:
        doc.add_heading(section, level=2)
        doc.add_paragraph(desc)

    doc.add_heading("Reference Snippets", level=1)
    if rag_chunks:
        for idx, chunk in enumerate(rag_chunks[:8], start=1):
            doc.add_heading(f"Snippet {idx}", level=2)
            p = doc.add_paragraph(str(chunk)[:500])
            if p.runs:
                p.runs[0].font.color.rgb = RGBColor(0x55, 0x55, 0x55)
    else:
        doc.add_paragraph("No retrieval snippets were provided for this generation.")

    if evidence_entries:
        doc.add_heading("Reference Evidence", level=1)
        for item in evidence_entries[:20]:
            file_name = str(item.get("file_name") or "unknown")
            location = str(item.get("page_or_slide") or "unknown")
            snippet = str(item.get("snippet") or "")[:260]
            p = doc.add_paragraph(style="List Number")
            p.add_run(f"{file_name} | {location}\n{snippet}")

    footer = doc.add_paragraph(f"Generated by FastPPT on {today}")
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    if footer.runs:
        footer.runs[0].font.size = Pt(9)
        footer.runs[0].font.color.rgb = RGBColor(0x99, 0x99, 0x99)

    doc.save(output_path)
    return output_path
