const express = require('express');
const cors = require('cors');
const morgan = require('morgan');
const fs = require('fs');
const path = require('path');
const pptxgen = require('pptxgenjs');

const app = express();
const PORT = process.env.PORT || 3000;
const LOG_LEVEL = process.env.LOG_LEVEL || 'info';

// Middleware
app.use(cors());
app.use(express.json({ limit: '50mb' }));
app.use(morgan('combined'));

// Ensure temp directory exists
const tempDir = path.join(__dirname, 'temp');
if (!fs.existsSync(tempDir)) {
    fs.mkdirSync(tempDir, { recursive: true });
}

// Health check endpoint
app.get('/health', (req, res) => {
    res.json({
        status: 'healthy',
        service: 'pptxgenjs',
        timestamp: new Date().toISOString(),
        uptime: process.uptime()
    });
});

// Generate PPT endpoint
app.post('/api/generate-ppt', async (req, res) => {
    const startTime = Date.now();

    try {
        const { slides, title, author } = req.body;

        if (!slides || !Array.isArray(slides)) {
            return res.status(400).json({ error: 'Invalid slides data' });
        }

        const pptx = new pptxgen();

        // Set presentation properties
        pptx.author = author || 'FastPPT';
        pptx.title = title || 'Generated Presentation';
        pptx.subject = 'Auto-generated by FastPPT';

        // Generate slides
        slides.forEach((slideData, index) => {
            const slide = pptx.addSlide();

            // Add title
            if (slideData.title) {
                slide.addText(slideData.title, {
                    x: 0.5,
                    y: 0.5,
                    w: 9,
                    h: 1,
                    fontSize: 32,
                    bold: true,
                    color: '363636'
                });
            }

            // Add content
            if (slideData.content) {
                slide.addText(slideData.content, {
                    x: 0.5,
                    y: 2,
                    w: 9,
                    h: 4,
                    fontSize: 18,
                    color: '666666',
                    valign: 'top'
                });
            }

            // Add bullet points
            if (slideData.bullets && Array.isArray(slideData.bullets)) {
                slide.addText(slideData.bullets.map(b => ({ text: b, options: { bullet: true } })), {
                    x: 0.5,
                    y: 2,
                    w: 9,
                    h: 4,
                    fontSize: 16,
                    color: '666666'
                });
            }
        });

        // Generate file
        const filename = `ppt_${Date.now()}.pptx`;
        const filepath = path.join(tempDir, filename);

        await pptx.writeFile({ fileName: filepath });

        // Read file and send as base64
        const fileBuffer = fs.readFileSync(filepath);
        const base64 = fileBuffer.toString('base64');

        // Clean up temp file
        fs.unlinkSync(filepath);

        const duration = Date.now() - startTime;

        res.json({
            success: true,
            filename,
            data: base64,
            slides_count: slides.length,
            duration_ms: duration
        });

    } catch (error) {
        console.error('PPT generation error:', error);
        res.status(500).json({
            error: 'Failed to generate PPT',
            message: error.message
        });
    }
});

// Metrics endpoint
app.get('/metrics', (req, res) => {
    const memUsage = process.memoryUsage();

    res.json({
        service: 'pptxgenjs',
        uptime_seconds: process.uptime(),
        memory: {
            rss_mb: Math.round(memUsage.rss / 1024 / 1024),
            heap_used_mb: Math.round(memUsage.heapUsed / 1024 / 1024),
            heap_total_mb: Math.round(memUsage.heapTotal / 1024 / 1024)
        },
        timestamp: new Date().toISOString()
    });
});

// Start server
app.listen(PORT, () => {
    console.log(`PPTXGenJS service running on port ${PORT}`);
    console.log(`Environment: ${process.env.NODE_ENV || 'development'}`);
    console.log(`Log level: ${LOG_LEVEL}`);
});

// Graceful shutdown
process.on('SIGTERM', () => {
    console.log('SIGTERM received, shutting down gracefully...');
    process.exit(0);
});

process.on('SIGINT', () => {
    console.log('SIGINT received, shutting down gracefully...');
    process.exit(0);
});
