const express = require('express');
const cors = require('cors');
const morgan = require('morgan');
const fs = require('fs');
const path = require('path');
const pptxgen = require('pptxgenjs');

const app = express();
const PORT = process.env.PORT || 3000;
const LOG_LEVEL = process.env.LOG_LEVEL || 'info';

// Middleware
app.use(cors());
app.use(express.json({ limit: '50mb' }));
app.use(morgan('combined'));

// Ensure temp directory exists
const tempDir = path.join(__dirname, 'temp');
if (!fs.existsSync(tempDir)) {
    fs.mkdirSync(tempDir, { recursive: true });
}

// Health check endpoint
app.get('/health', (req, res) => {
    res.json({
        status: 'healthy',
        service: 'pptxgenjs',
        timestamp: new Date().toISOString(),
        uptime: process.uptime()
    });
});

function renderSlide(slide, slideData) {
    if (!slideData || typeof slideData !== 'object') return;

    const title = slideData.title || '';
    if (title) {
        slide.addText(title, {
            x: 0.5,
            y: 0.5,
            w: 9,
            h: 1,
            fontSize: 32,
            bold: true,
            color: '363636'
        });
    }

    if (Array.isArray(slideData.bullets) && slideData.bullets.length) {
        slide.addText(slideData.bullets.map((b) => ({ text: String(b), options: { bullet: true } })), {
            x: 0.5,
            y: 2,
            w: 9,
            h: 4,
            fontSize: 16,
            color: '666666'
        });
        return;
    }

    if (slideData.content) {
        slide.addText(String(slideData.content), {
            x: 0.5,
            y: 2,
            w: 9,
            h: 4,
            fontSize: 18,
            color: '666666',
            valign: 'top'
        });
    }
}

function mapPageToSimpleSlide(page) {
    const type = page?.type || 'content';
    if (type === 'cover') {
        return { title: page.title || '', content: page.subtitle || '' };
    }
    if (type === 'agenda') {
        return { title: page.title || '目录', bullets: Array.isArray(page.items) ? page.items : [] };
    }
    if (type === 'summary') {
        return { title: page.title || '总结', bullets: Array.isArray(page.takeaways) ? page.takeaways : [] };
    }
    if (type === 'example') {
        const bullets = [];
        if (page.problem) bullets.push(`题目：${page.problem}`);
        if (Array.isArray(page.steps)) bullets.push(...page.steps.map((s) => `步骤：${s}`));
        if (page.answer) bullets.push(`答案：${page.answer}`);
        return { title: page.title || '案例', bullets };
    }
    if (type === 'code') {
        return { title: page.title || '代码示例', content: page.code || '' };
    }
    if (type === 'formula') {
        const formulas = Array.isArray(page.formulas) ? page.formulas : [];
        const bullets = formulas.map((item) => {
            if (item && typeof item === 'object') {
                return `${item.label || '公式'}：${item.expr || ''}`;
            }
            return String(item || '');
        });
        return { title: page.title || '公式', bullets };
    }
    if (type === 'two_column') {
        const left = page.left || {};
        const right = page.right || {};
        const bullets = [
            ...(Array.isArray(left.points) ? left.points.map((p) => `左：${p}`) : []),
            ...(Array.isArray(right.points) ? right.points.map((p) => `右：${p}`) : []),
        ];
        return { title: page.title || '对比', bullets };
    }
    if (type === 'quote') {
        return { title: page.title || '引言', content: page.text || '' };
    }
    return {
        title: page.title || '内容页',
        bullets: Array.isArray(page.bullets) ? page.bullets : [],
        content: page.tip || ''
    };
}

function buildPptx({ slides, title, author, subject }) {
    const pptx = new pptxgen();
    pptx.layout = 'LAYOUT_WIDE';
    pptx.author = author || 'FastPPT';
    pptx.title = title || 'Generated Presentation';
    pptx.subject = subject || 'Auto-generated by FastPPT';

    slides.forEach((slideData) => {
        const slide = pptx.addSlide();
        renderSlide(slide, slideData);
    });
    return pptx;
}

// New compatible endpoint for backend: returns binary pptx
app.post('/generate', async (req, res) => {
    const startTime = Date.now();

    try {
        const pages = Array.isArray(req.body?.pages)
            ? req.body.pages
            : (Array.isArray(req.body?.slides) ? req.body.slides : []);
        if (!pages.length) {
            return res.status(400).json({ error: 'Invalid pages data' });
        }

        const teachingSpec = req.body?.teaching_spec || {};
        const metadata = req.body?.metadata || {};
        const slides = pages.map(mapPageToSimpleSlide);
        const filename = metadata.filename || `ppt_${Date.now()}.pptx`;
        const pptx = buildPptx({
            slides,
            title: metadata.title || teachingSpec.title || 'Generated Presentation',
            author: metadata.author || teachingSpec.teacher || 'FastPPT',
            subject: teachingSpec.subject || metadata.subject || ''
        });

        const buffer = await pptx.write({ outputType: 'nodebuffer', compression: true });
        const duration = Date.now() - startTime;

        res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.presentationml.presentation');
        res.setHeader('Content-Disposition', `attachment; filename="${encodeURIComponent(filename)}"`);
        res.setHeader('X-Generation-Time', duration);
        res.send(buffer);
    } catch (error) {
        console.error('PPT generation error (/generate):', error);
        res.status(500).json({
            error: 'Failed to generate PPT',
            message: error.message
        });
    }
});

// Legacy endpoint: returns JSON with base64
app.post('/api/generate-ppt', async (req, res) => {
    const startTime = Date.now();

    try {
        const slides = Array.isArray(req.body?.slides) ? req.body.slides : [];
        if (!slides.length) {
            return res.status(400).json({ error: 'Invalid slides data' });
        }

        const title = req.body?.title || 'Generated Presentation';
        const author = req.body?.author || 'FastPPT';
        const filename = `ppt_${Date.now()}.pptx`;

        const pptx = buildPptx({
            slides,
            title,
            author,
            subject: 'Auto-generated by FastPPT'
        });

        const fileBuffer = await pptx.write({ outputType: 'nodebuffer', compression: true });
        const base64 = Buffer.from(fileBuffer).toString('base64');
        const duration = Date.now() - startTime;

        res.json({
            success: true,
            filename,
            data: base64,
            slides_count: slides.length,
            duration_ms: duration
        });
    } catch (error) {
        console.error('PPT generation error (/api/generate-ppt):', error);
        res.status(500).json({
            error: 'Failed to generate PPT',
            message: error.message
        });
    }
});

// Metrics endpoint
app.get('/metrics', (req, res) => {
    const memUsage = process.memoryUsage();

    res.json({
        service: 'pptxgenjs',
        uptime_seconds: process.uptime(),
        memory: {
            rss_mb: Math.round(memUsage.rss / 1024 / 1024),
            heap_used_mb: Math.round(memUsage.heapUsed / 1024 / 1024),
            heap_total_mb: Math.round(memUsage.heapTotal / 1024 / 1024)
        },
        timestamp: new Date().toISOString()
    });
});

// Start server
app.listen(PORT, () => {
    console.log(`PPTXGenJS service running on port ${PORT}`);
    console.log(`Environment: ${process.env.NODE_ENV || 'development'}`);
    console.log(`Log level: ${LOG_LEVEL}`);
});

// Graceful shutdown
process.on('SIGTERM', () => {
    console.log('SIGTERM received, shutting down gracefully...');
    process.exit(0);
});

process.on('SIGINT', () => {
    console.log('SIGINT received, shutting down gracefully...');
    process.exit(0);
});
